### ISSUE TITLE
Initialization Issue

### ISSUE THREAD

**Issue by fredfortier** [enigmampc/discovery-cli#3]
* OS: `Linux localhost.localdomain 5.1.8-300.fc30.x86_64`
* Node: `v11.14.0`

```
$ discovery init
...
Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN myproject@1.0.0 No description
npm WARN myproject@1.0.0 No repository field.

added 411 packages from 321 contributors and audited 227299 packages in 25.14s
found 0 vulnerabilities

? Running in SGX Hardware (HW) or Software (SW) mode? (HW/sw) HW
? About to pull Docker images. This requires 15 GB of space. Continue? (Y/n) Y
Pulling Enigma Docker images...
(node:4281) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'row' of undefined
    at Object.module.exports.pullImage (/home/fredfortier/Code/Enigma/discovery/genesis-game-client/env/lib/node_modules/@enigmampc/discovery-cli/src/docker.js:64:33)
    at /home/fredfortier/Code/Enigma/discovery/genesis-game-client/env/lib/node_modules/@enigmampc/discovery-cli/src/index.js:164:18
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:4281) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
```

**Comment by lacabra** [comment]
Thanks @fredfortier. Unfortunately, I cannot replicate this error. And the specific line that triggers is from the [get-cursor-position](https://www.npmjs.com/package/get-cursor-position) package that reads the cursor position from the terminal. I have tested this successfully in both Mac/BSD and Ubuntu. 

Is there anything specific about your terminal/xterm setup that could cause this to fail?

**Comment by fredfortier** [comment]
This was a Docker issue.
