### ISSUE TITLE
Error for the installation of the discovery CLI

### ISSUE THREAD

**Issue by ValentinDelpy** [enigmampc/discovery-cli#46]
Hi. I'm under Windows 10, using NPM v6.11.3 and Node.js 11.14.0 and trying to install the discovery CLI throught the command line in the tutorials. But I have this error :

`gyp ERR! build error
gyp ERR! stack Error: C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\Soul\AppData\Roaming\npm\node_modules\@enigmampc\discovery-cli\node_modules\get-cursor-position
gyp ERR! node -v v12.11.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok
npm WARN acorn-jsx@5.2.0 requires a peer of acorn@^6.0.0 || ^7.0.0 but none is installed. You must install peer dependencies yourself.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! get-cursor-position@1.0.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the get-cursor-position@1.0.5 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Soul\AppData\Roaming\npm-cache\_logs\2020-05-08T08_17_12_663Z-debug.log`
`

Can anyone help me ? Looks similar to another issue, but not on the same environment.

**Comment by ValentinDelpy** [comment]
npm was not using the good node version.
