### ISSUE TITLE
discovery init followed by start error

### ISSUE THREAD

**Issue by sghanem-123** [enigmampc/discovery-cli#48]
windows platform

here is the output

D:\Enigma\millionaires_problem_demo>discovery init
                                                                            .:.
    ______      _                                                      .::::-:/:.
   / ____/___  (_)___ _____ ___  ____ _                            .:::-       .:/:.
  / __/ / __ \/ / __ `/ __ `__ \/ __ `/                        .:::-      .-      .//:
 / /___/ / / / / /_/ / / / / / / /_/ /                     .:::-          :          .//:
/_____/_/ /_/_/\__, /_/ /_/ /_/\__,_/                    /o:           -::/-           -/s
              /____/                                    -/ ://.    -:::.   -//.    -:::.-/
    ____             __                   __            +     :/+/:.          :o/::.    +
   / __ \_________  / /_____  _________  / /           /-      /-:/:.      -:::/.      /-
  / /_/ / ___/ __ \/ __/ __ \/ ___/ __ \/ /           .+      .+   .:/:-:::.  ./      .+
 / ____/ /  / /_/ / /_/ /_/ / /__/ /_/ / /            +.      +.      +.      /.      +.
/_/   /_/   \____/\__/\____/\___/\____/_/            -:      -/      -/      -:      -/
                                                     +     - :/:     +    .:::-.     +
    ____  _                                         /-. .-     .//- /-.:::-     -.. /-
   / __ \(_)_____________ _   _____  _______  __    o.-           -/o:-           ::/
  / / / / / ___/ ___/ __ \ | / / _ \/ ___/ / / /     ://.          +.         -:::-
 / /_/ / (__  ) /__/ /_/ / |/ /  __/ /  / /_/ /         ://.      -/      -:::.
/_____/_/____/\___/\____/|___/\___/_/   \__, /            .:/:.   +   -:::.
                                       /____/                .:/://:::.
                                                                 .:.

? Set up the Discovery Enigma Protocol development environment in the current folder? (Y/n) y
Checking if "docker" is installed in the system... FOUND
Checking if "docker-compose" is installed in the system... FOUND
Checking if "rustc" is installed in the system... FOUND
Checking if "cargo" is installed in the system... FOUND
Checking if "rustup" is installed in the system... FOUND
Checking if "npm" is installed in the system... FOUND
Checking if "git" is installed in the system... FOUND
Checking if Rust "nightly-2019-08-01" is installed in the system... FOUND
Checking for Rust wasm32-unknown-unknown...
info: component 'rust-std' for target 'wasm32-unknown-unknown' is up to date
Downloading files...
Installing package dependendecies...
{ Error: spawn npm ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:247:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn npm',
  path: 'npm',
  spawnargs: [ 'install' ] }
? Running in SGX Hardware (HW) or Software (SW) mode? (HW/sw) sw
(node:1000) UnhandledPromiseRejectionWarning: Error: EPERM: operation not permitted, symlink 'docker-compose.cli-sw.yml' -> 'docker-compose.yml'
    at Object.symlinkSync (fs.js:925:3)
    at inquirer.prompt.then.answer (d:\nvm\nvm\v11.15.0\node_modules\@enigmampc\discovery-cli\src\index.js:166:10)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1000) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1000) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

D:\Enigma\millionaires_problem_demo>discovery start
Cannot find the expected directory structure.

**Comment by sghanem-123** [comment]
any idea what causes the error please
